#!/usr/bin/env bash

# shellcheck source=./lib/bash/core.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

# shellcheck source=./lib/bash/templates.sh

# shellcheck source=./lib/bash/go.sh
source "${BASH_SOURCE[0]%/*}/../lib/bash/go.sh"

function main() {

  echo -e "${OK_COLOR}==> Building app..."

  # if ! loadAWSSecrets "run"; then
  #   echo "No secret found."
  # fi

  export GOPATH="${HOME}/go"

  export GO111MODULE="on"

  GO="$(command -v "go")"
  (
    set -x
    "${GO}" version
  )

  local DIR
  DIR="$(jq --raw-output ".dir" "./project.config.json")"
  CURDIR="$(pwd)"
  (
    set -x
    mkdir ./build
  )

  for FILE in $(jq --raw-output ".targets[]" "./project.config.json"); do

    local BUILT_FILE="${FILE}"
    BUILT_FILE="${BUILT_FILE/\/src\///build/}"
    BUILT_FILE="${CURDIR}/${BUILT_FILE/.go/}"

    (
      set -x
      cd "${DIR}"
      "${GO}" build \
        -o "${BUILT_FILE}" \
        "${FILE}" \
        "$@"
      cd "${CURDIR}"
    )

    if command -v "upx" >/dev/null; then
      echo "attempt to compress"
      (
        set -x
        upx -9 "${BUILT_FILE}"
      )
    fi

    (
      set -x
      cp "${BUILT_FILE}" ./build/appBuilt
    )
  done

}

main "$@"