#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}/../lib/bash/core.sh"

source "${BASH_SOURCE[0]%/*}/../lib/bash/go.sh"

function main() {

 echo -e "${OK_COLOR}==> Installing dependencies..."
  echo ${HOME}
  export GOPATH="${HOME}/go"

  export GO111MODULE="on"

  GO="$(command -v "go")"
  local DIR
  DIR="$(jq --raw-output ".dir" "./project.config.json")"

  (
    set -x
    cd "${DIR}"
    "${GO}" mod tidy
  )
}

main   "$@"
